# ------------------------------------
# OpenRouter settings
# ------------------------------------
openrouter: True # OpenRouterを使用するかどうか / Falseの場合はローカルサーバーを使用
openrouter_api_key: "api_key"
openrouter_server_url: "https://openrouter.ai/api/v1"
openrouter_model_name: "qwen/qwen3.5-27b" # thinkingモデルを使うこと

# ------------------------------------
# Local server settings
# ------------------------------------
SERVER_URL: "http://<server_ip>:<server_port>/v1"
MODEL_NAME: "Qwen3-30B-A3B-Instruct-2507"

# ------------------------------------
# Inference config
# ------------------------------------
infer_config:
  max_tokens: 4096
  temperature: 0
  top_p: 1.0
batch_size: 8

# ------------------------------------
# Prompts
# ------------------------------------
prompts: # 処理の順に並べること
  - question_prompt: ./prompts/create_qa/qa_create_question.md
  - thinking_prompt: ./prompts/create_qa/qa_create_thinking.md
  - answer_prompt: ./prompts/create_qa/qa_create_answer.md
  - refine_answer_prompt: ./prompts/create_qa/qa_refine_answer.md
  - eval_prompt: ./prompts/create_qa/eval.md
# ------------------------------------
# Output
# ------------------------------------
output_path: ./test_output/imabari_qa

# ------------------------------------
# Retry settings
# ------------------------------------

max_retries: 3
wait_seconds: 5
